### ISSUE TITLE
Set up your Kanban board

### ISSUE THREAD

**Issue by Yulianav09** [Yulianav09/Group-capstone#21]
### Set up your Kanban board

This is the link to our GitHub project.
https://github.com/Yulianav09/Group-capstone/projects/1

We are a group of 2 people, Yuliana and Obiba

**Comment by Lizdev-05** [comment]
Hi @Yulianav09 and @obibaadoma , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/YYht2UTV41u1vxHTss/giphy-downsized-medium.gif"/>

## Highlights
:heavy_check_mark: Descriptive issue:+1: 

## Required Changes ♻️
_Check the comments under the review._

- [x] Please since you are a team of  **two** people, all cards with the `Student C` suffix on the template were removed from students' copy of the template.
- [x] Kindly ensure that cards are assigned to team members in a fair way:
    * First you need to decide who is `Student A`, and `Student B`. So each card with `Student A` in its title should always be assigned to the same student (and analogical for other students).
    * All cards with `group task` in the title should be assigned to someone (it does not matter to whom as students had freedom with that).

You should see a circle with the user's avatar on each card after assigning the cards to team members. See the example below:

  ![image](https://github.com/Yulianav09/Group-capstone/assets/73854999/ef6b9e5d-a358-4afe-883d-98a637ba7bb8)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Yulianav09** [comment]
Thank you very much, we are going to change it

**Comment by OyePriscilla** [comment]
Hi @Yulianav09 and @obibaadoma 👏 👏, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Assigned task to all group members ✔️ 

 ## Required Changes ♻️

### **As pointed out earlier, kindly remove all the cards with students C label for the sake of clarity. 👇** 

<img width="272" alt="Untitled" src="https://github.com/Yulianav09/Group-capstone/assets/103386183/333d94ee-e584-4e00-80b4-8323228d84dd">



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Yulianav09** [comment]
Ok thanks for the review, we will change it

**Comment by LionRouge1** [comment]
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Highlights
- Great job, your project is error free :+1: 
- Nice work you meet all the requirements :1st_place_medal: 
- All linters passed :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
